name: ğŸš€ Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¦ Checkout Repository
      uses: actions/checkout@v3

    - name: ğŸ” Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}

    - name: Git safe directory
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} "git config --global --add safe.directory /var/www/lqms"

    - name: ğŸš€ Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} << 'EOF'
          cd /var/www/lqms
          
          # Wenn das Repository nicht existiert, initialisiere es
          if [ ! -d ".git" ]; then
            git init
            git remote add origin git@github.com:/nyrocarion/LQMS.git
          fi
          git pull origin main
          npm install
          npm run build
        EOF
